#! /bin/bash
xterm -e "python3 oled.py etc/room_setup.json" &
sleep 1
xterm -e "python3 main.py etc/room_setup.json ds18b20 4" &
sleep 1
xterm -e "python3 main.py etc/room_setup.json dht22 17" &
sleep 1
xterm -e "python3 main.py etc/room_setup.json revC /dev/ttyACM0" &
sleep 1
xterm -e "python3 main.py etc/room_setup.json max76675 /dev/ttyACM0" 


